[features]
seeds = false
skip-lint = false

[programs.devnet]
todo_list_app = "7xZfx4ZGnCiHVeBKhk58MXQ6iRrjdRnxgB29rqLfRZ5a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
